
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tuhin
 */
public class Home_Page extends javax.swing.JFrame {

    /**
     * Creates new form Home_Page
     */
    public Home_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Book_now = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        supply_chain = new javax.swing.JLabel();
        overview = new javax.swing.JLabel();
        digital_services = new javax.swing.JLabel();
        transport = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        Find_local_office = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        CLS_Book = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        admin = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        Tracking = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        Profile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Services & Information");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel48.setText("About us");
        jPanel2.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 100, 40));

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel49.setText("Contact us");
        jPanel2.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 120, 40));

        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel50.setText("Data Privacy Notification");
        jPanel2.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 130, -1, -1));

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel51.setText("Terms & conditions");
        jPanel2.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 70, -1, -1));

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel52.setText("Press");
        jPanel2.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 130, 80, -1));

        jLabel53.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel53.setText("Brand protection");
        jPanel2.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 200, -1, 30));

        jLabel54.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel54.setText("News & advisories");
        jPanel2.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jLabel55.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel55.setText("Container tracking");
        jPanel2.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 50, -1, 50));

        jLabel56.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel56.setText("Logistics explained");
        jPanel2.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        jLabel57.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel57.setText("Support");
        jPanel2.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, -1, -1));

        jLabel58.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel58.setText("Transportation Services");
        jPanel2.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 200, -1, -1));

        jLabel59.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel59.setText("Supply Chain and Logistics");
        jPanel2.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tuhin\\Desktop\\as\\facebook logo.png")); // NOI18N
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tuhin\\Desktop\\as\\linkedin logo.png")); // NOI18N
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tuhin\\Desktop\\as\\twitter logo.png")); // NOI18N
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 250, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 1241, 1420, 320));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 255, 51));
        jButton4.setText("Instant Prices");
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 405, -1, 39));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tuhin\\Desktop\\as\\delivery1111.jpg")); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 31, -1, 190));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Ocean and Shipping Spot");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 239, 290, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Book your Ocean & Inland shipments");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("online at fixed container shipping prices");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 299, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("and with a loading guarantee to know");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 328, 310, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("when they will arrive.");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 357, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1227, 241, 330, 460));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tuhin\\Desktop\\as\\load.jpeg")); // NOI18N
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 26, -1, -1));

        Book_now.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Book_now.setForeground(new java.awt.Color(51, 255, 0));
        Book_now.setText("Book now");
        Book_now.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_nowActionPerformed(evt);
            }
        });
        jPanel4.add(Book_now, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 407, -1, 37));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Less-Than-Container Load (LCL)");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 340, 33));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("With Shipping cargo Less-Than-Con- ");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 330, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("tainer Load you have the flexibility to");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 300, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("ship small amounts of cargo quickly ");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("based on your needs.");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, 18));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1587, 241, 330, 460));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        supply_chain.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        supply_chain.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tuhin\\Desktop\\as\\route logo.png")); // NOI18N
        supply_chain.setText("Supply Chain and Logistics");
        supply_chain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supply_chainMouseClicked(evt);
            }
        });
        jPanel5.add(supply_chain, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 320, -1));

        overview.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        overview.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tuhin\\Desktop\\as\\user (logo1).png")); // NOI18N
        overview.setText("Overview");
        overview.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                overviewAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        overview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                overviewMouseClicked(evt);
            }
        });
        jPanel5.add(overview, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 260, -1));

        digital_services.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        digital_services.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tuhin\\Desktop\\as\\agreement logo 30.png")); // NOI18N
        digital_services.setText("Digital Service");
        jPanel5.add(digital_services, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 240, 60));

        transport.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        transport.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tuhin\\Desktop\\as\\delivery logo.png")); // NOI18N
        transport.setText("Transportation Services");
        transport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transportMouseClicked(evt);
            }
        });
        jPanel5.add(transport, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 290, -1));

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(153, 153, 153));
        jLabel60.setText("SUPPORT");
        jPanel5.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 100, 30));

        Find_local_office.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Find_local_office.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tuhin\\Desktop\\as\\office-building logo 30.png")); // NOI18N
        Find_local_office.setText("Find local office");
        jPanel5.add(Find_local_office, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 210, 50));

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel62.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tuhin\\Desktop\\as\\adminuser.png")); // NOI18N
        jLabel62.setText("Admin Use");
        jLabel62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel62MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 190, 50));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 241, -1, 970));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tuhin\\Desktop\\as\\ship.png")); // NOI18N
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 305, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Container Load  in Ship (CLS)");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 330, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 153, 153));
        jLabel19.setText("Request a shipping quote for an ocean");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 274, 320, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 153, 153));
        jLabel20.setText("shipment that exceeds the dimensions");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 303, 310, -1));

        CLS_Book.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        CLS_Book.setForeground(new java.awt.Color(51, 204, 0));
        CLS_Book.setText("Book Now");
        CLS_Book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CLS_BookMouseClicked(evt);
            }
        });
        jPanel6.add(CLS_Book, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 406, -1, 38));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setText("of our standard containers.");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 332, -1, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(857, 241, -1, 460));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("FEATURED");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(887, 181, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel23.setText("Container Shipping Rates for Transportation and Integrated Logistics Services");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(877, 211, 830, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("POPULAR");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(877, 731, 90, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel25.setText("Popular in Supply chain & logistics");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(877, 761, 390, 30));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tuhin\\Desktop\\as\\document2222.png")); // NOI18N
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 8, -1, 92));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 51, 51));
        jLabel32.setText("Customer Services");
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 51, 194, 40));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(153, 153, 153));
        jLabel33.setText("Our Customs Services can help every");
        jPanel7.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(153, 153, 153));
        jLabel34.setText("importer and exporter that needs to");
        jPanel7.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 290, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(153, 153, 153));
        jLabel35.setText("have customs clearance and expedite");
        jPanel7.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton8.setForeground(new java.awt.Color(51, 204, 0));
        jButton8.setText("Get a quote");
        jPanel7.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 326, -1, 40));

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(153, 153, 153));
        jLabel40.setText("this process at both origin and");
        jPanel7.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(153, 153, 153));
        jLabel41.setText("destination.");
        jPanel7.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1237, 821, 320, 390));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tuhin\\Desktop\\as\\speedometer1.png")); // NOI18N
        jPanel8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, 73, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("Cold Chain Logistics");
        jPanel8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 51, 212, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(153, 153, 153));
        jLabel30.setText("End to end temperature controlled");
        jPanel8.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 161, -1, -1));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(153, 153, 153));
        jLabel31.setText("supply chain for your sensitive cargo.");
        jPanel8.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 201, -1, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton7.setForeground(new java.awt.Color(51, 204, 0));
        jButton7.setText("Contact us");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, 38));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(867, 821, 340, 390));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tuhin\\Desktop\\as\\admin.png")); // NOI18N
        jPanel9.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 16, 70, 68));

        admin.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        admin.setForeground(new java.awt.Color(51, 204, 0));
        admin.setText("Contact us");
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        jPanel9.add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, 40));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(51, 51, 51));
        jLabel36.setText("Admin Panel");
        jPanel9.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 190, 30));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(153, 153, 153));
        jLabel38.setText("Registered employees con only ");
        jPanel9.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(153, 153, 153));
        jLabel39.setText("access the admin panel.");
        jPanel9.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(153, 153, 153));
        jLabel42.setText("Besides, it is better to try not to enter ");
        jPanel9.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(153, 153, 153));
        jLabel43.setText("the user admin panel");
        jPanel9.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 30));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1587, 821, 330, 390));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tuhin\\Desktop\\as\\Shiping cargo logo.png")); // NOI18N
        jPanel10.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 76));

        jLabel47.setFont(new java.awt.Font("Tahoma", 3, 27)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(102, 102, 102));
        jLabel47.setText("Shipping Cargo");
        jPanel10.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 223, 50));

        home.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tuhin\\Desktop\\as\\home11.png")); // NOI18N
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        jPanel10.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 10, -1, -1));

        Search.setBackground(new java.awt.Color(255, 255, 255));
        Search.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tuhin\\Desktop\\as\\search.png")); // NOI18N
        jPanel10.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, -1, -1));

        Tracking.setBackground(new java.awt.Color(255, 255, 255));
        Tracking.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tuhin\\Desktop\\as\\placeholder.png")); // NOI18N
        Tracking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrackingActionPerformed(evt);
            }
        });
        jPanel10.add(Tracking, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, -1, -1));

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setText("Search............");
        jPanel10.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 670, 50));

        Profile.setBackground(new java.awt.Color(255, 255, 255));
        Profile.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tuhin\\Desktop\\as\\user.png")); // NOI18N
        Profile.setOpaque(false);
        Profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfileMouseClicked(evt);
            }
        });
        Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileActionPerformed(evt);
            }
        });
        jPanel10.add(Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 10, -1, -1));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 95, 1450, -1));

        jScrollPane2.setViewportView(jPanel1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-420, 20, 2100, 1110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Book_nowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_nowActionPerformed
        this.dispose();
        LCL_book book = new LCL_book();
        book.setVisible(true);
    }//GEN-LAST:event_Book_nowActionPerformed

    private void ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileActionPerformed
       this.dispose();
       Profile p = new Profile();
       p.setVisible(true);
    }//GEN-LAST:event_ProfileActionPerformed

    private void TrackingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrackingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrackingActionPerformed

    private void overviewAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_overviewAncestorMoved
       
    }//GEN-LAST:event_overviewAncestorMoved

    private void overviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_overviewMouseClicked
       this.dispose();
       Home_Page home = new Home_Page();
       home.setVisible(true);
    }//GEN-LAST:event_overviewMouseClicked

    private void transportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transportMouseClicked
        this.dispose();
        Transportation_Services transport = new Transportation_Services();
        transport.setVisible(true);
    }//GEN-LAST:event_transportMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
       this.dispose();
       Home_Page h = new Home_Page();
       h.setVisible(true);
    }//GEN-LAST:event_homeMouseClicked

    private void ProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileMouseClicked
        this.dispose();
       Profile P = new Profile();
       P.setVisible(true);
    }//GEN-LAST:event_ProfileMouseClicked

    private void CLS_BookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLS_BookMouseClicked
        this.dispose();
        CLS c = new CLS();
        c.setVisible(true);
    }//GEN-LAST:event_CLS_BookMouseClicked

    private void supply_chainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supply_chainMouseClicked
        Supply_Chain s = null;
        try {
            s = new Supply_Chain();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Home_Page.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Home_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
        s.setVisible(true);
       
    }//GEN-LAST:event_supply_chainMouseClicked

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
       this.dispose();
       Login_Employee le = new Login_Employee();
       le.setVisible(true);
    }//GEN-LAST:event_adminActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       this.dispose();
       CCL c= new CCL();
       c.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jLabel62MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel62MouseClicked
        this.dispose();
        Login_Employee H = new Login_Employee();
        H.setVisible(true);
    }//GEN-LAST:event_jLabel62MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Book_now;
    private javax.swing.JButton CLS_Book;
    private javax.swing.JLabel Find_local_office;
    private javax.swing.JButton Profile;
    private javax.swing.JButton Search;
    private javax.swing.JButton Tracking;
    private javax.swing.JButton admin;
    private javax.swing.JLabel digital_services;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel overview;
    private javax.swing.JLabel supply_chain;
    private javax.swing.JLabel transport;
    // End of variables declaration//GEN-END:variables
}
