
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tuhin
 */
public class LCL_book extends javax.swing.JFrame {

    String path=null;
    byte[] img2=null;
    public LCL_book() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Profile = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        contiune = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        company = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        zipcode = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        port = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        productdetails = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        weight = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        country = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        Println = new javax.swing.JTextArea();
        Print = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Shipping Cargo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 240, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tuhin\\Desktop\\as\\Shiping cargo logo.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 70, 80));

        Profile.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tuhin\\Desktop\\as\\user.png")); // NOI18N
        jPanel1.add(Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 60, 60));

        Back.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Back.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tuhin\\Desktop\\as\\previous icon.png")); // NOI18N
        Back.setText("Back");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1060, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Less-Than-Container Load (LCL) Booking");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 1060, 60));

        contiune.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        contiune.setText("Continue");
        contiune.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contiuneMouseClicked(evt);
            }
        });
        jPanel3.add(contiune, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 1160, 350, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Company Name");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Street Address ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("City");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 60, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("Postal / ZIP Code");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("Country");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 640, -1, -1));

        company.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyActionPerformed(evt);
            }
        });
        jPanel3.add(company, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 610, 60));

        address.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel3.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 610, 60));

        city.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel3.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 610, 60));

        zipcode.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel3.add(zipcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, 610, 60));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel11.setText("Port Name");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 750, -1, -1));

        port.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel3.add(port, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 780, 610, 60));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel12.setText("Product details");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 860, -1, -1));

        productdetails.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        productdetails.setText("All details");
        jPanel3.add(productdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 890, 600, 190));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel13.setText("Weight");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1100, -1, -1));

        weight.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        weight.setText("..........KG");
        jPanel3.add(weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 1090, 140, 50));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel14.setText("Date line");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 1100, 90, -1));

        date.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        date.setText("DD.MM.YY");
        jPanel3.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 1090, 300, 50));

        country.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        country.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Country", "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Brazil", "Cambodia", "Cameroon", "Canada", "China", "Colombia", "Denmark", "Eritrea", "Finland", "France", "Germany", "Ghana", "Honduras", "Hungary", "Iceland", "India", "Iran", "Iraq", "Ireland", "Italy", "Japan", "Jordan", "Kiribati", "Kuwait", "Laos", "Lebanon", "Liberia", "Libya", "Mexico", "Micronesia", "Myanmar", "Netherlands", "New Zealand", "North Korea", "Oman", "Pakistan", "Panama", "Poland", "Qatar", "Russia", "Saudi Arabia", "Somalia", "South Africa", "South Korea", "Spain", "Sri Lanka", "Sudan", "Switzerland", "Thailand", "Timor-Leste", "Togo", "United Arab Emirates", "United Kingdom", "United States of America", "Uzbekistan", "Vanuatu", "Venezuela", "Yemen", "Zambia" }));
        jPanel3.add(country, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 670, 600, 60));

        Println.setColumns(20);
        Println.setRows(5);
        jScrollPane2.setViewportView(Println);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 250, 560, 650));

        Print.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        Print.setText("Print");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });
        jPanel3.add(Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 930, 150, 50));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton1.setText("Confram Latter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 930, 180, 50));

        jScrollPane1.setViewportView(jPanel3);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -20, 1430, 1050));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
       this.dispose();
       Home_Page H = new Home_Page();
       H.setVisible(true);
    }//GEN-LAST:event_BackMouseClicked

    private void contiuneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contiuneMouseClicked
        String company1= company.getText();
        String address1=address.getText();
        String city1=city.getText();
        String zipcode1=zipcode.getText();
        String counrty1=(String)country.getSelectedItem();
        String port1=port.getText();
        String productdetails1=productdetails.getText();
        String weight1=weight.getText();
        String date1=date.getText();
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/shipping","root","");
            String query = "insert into lcl (Company,Address,City,Zip_code,Country,Port,Product,Weight,Date)values('"+company1+"','"+address1+"','"+city1+"','"+zipcode1+"','"+counrty1+"','"+port1+"','"+productdetails1+"','"+weight1+"','"+date1+"')";
            Statement stmt1=con.createStatement();
            
                int success= stmt1.executeUpdate(query);
                  if (success==1)
                  {
                      JOptionPane.showMessageDialog(this, "Booking Successful\nclick Confirm Leter");
                                 //this.dispose();
                             //new Home_Page().setVisible(true);
                  }
                  else
                  {
                      JOptionPane.showMessageDialog(this, "Bokking Not Successful");
                            
                  }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_contiuneMouseClicked

    private void companyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyActionPerformed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
       try {
            Println.print();                   
        } catch (PrinterException ex) {
            Logger.getLogger(LCL_book.class.getName()).log(Level.SEVERE, null, ex);
            this.dispose();
            new Home_Page().setVisible(true);
        }       
    }//GEN-LAST:event_PrintActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         Println.append
        (       "\t \t Shipping Cargo \n"+
            "\t \n"+
            ""+date.getText()+" \n"+
            ""+company.getText()+" \n"+
            ""+country.getSelectedItem()+""+
            ""+address.getText()+" \n"+
            ""+city.getText()+" \n"+
            ""+zipcode.getName()+"\n"+
                    
            "OBJECT: CONFIRMATION OF LESS-THEN-CONTANIAR LOAD  \n"+          
            "----------------------------------------------------------------------------------------------------------------------\n"+
            "Dear "+company.getText()+",\n\n"+
            "This letter shall confirm your acceptance of booking contanier communicated you on 22/06/2024 .\n\n"+
            "A copy of our purchase booking contaning the stated terms is attached.\n\n"+
            "Unless we receive objection within the days of your receipt of this booking, we shall consider the order \n"+
            "confirmed on its terms and shall expect delivery of all ordered goods on the sate indicated.\n\n\n\n "+
            " Sincerely,\n"+
            "MD. Antar\n"+
            "CEO of Shipping Cargo\n"+
            "PH: 01303015394\n"+
            "shippingcargo&gmail.com\n\n"
        ); 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LCL_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LCL_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LCL_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LCL_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LCL_book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Print;
    private javax.swing.JTextArea Println;
    private javax.swing.JLabel Profile;
    private javax.swing.JTextField address;
    private javax.swing.JTextField city;
    private javax.swing.JTextField company;
    private javax.swing.JButton contiune;
    private javax.swing.JComboBox<String> country;
    private javax.swing.JTextField date;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField port;
    private javax.swing.JTextField productdetails;
    private javax.swing.JTextField weight;
    private javax.swing.JTextField zipcode;
    // End of variables declaration//GEN-END:variables
}
